// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Nook",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Nook",
            targets: ["AppModule"],
            bundleIdentifier: "ping2o.Nook",
            teamIdentifier: "3X5K7V8H2L",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .motion(purposeString: "Nook monitors device movement to ensure you stay present during shared moments, notifying you if the focus is broken."),
                .microphone(purposeString: "Nook uses the microphone to measure ambient noise levels and detect silences, helping to trigger conversation prompts without recording any audio.")
            ],
            appCategory: .productivity
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)